require 'net/https'
require 'pp'
require 'set'
require 'cgi'
require 'uri'
require 'base64'
require 'rubygems'
require 'active_support/core_ext'
require 'json'

require 'sugarcrm/session'
require 'sugarcrm/module_methods'
require 'sugarcrm/connection_pool'
require 'sugarcrm/connection'
require 'sugarcrm/exceptions'
require 'sugarcrm/finders'
require 'sugarcrm/attributes'
require 'sugarcrm/associations'
require 'sugarcrm/module'
require 'sugarcrm/base'

