require 'pp'
require 'set'
require 'rubygems'
require 'active_support/core_ext'

require 'sugarcrm/module_methods'
require 'sugarcrm/base'
require 'sugarcrm/connection'
require 'sugarcrm/dynamic_finder_match'
require 'sugarcrm/exceptions'
require 'sugarcrm/module'
require 'sugarcrm/request'
require 'sugarcrm/response'
